### ISSUE TITLE
Improvement: CPM

### ISSUE THREAD

**Issue by vschwaberow** [matheusgomes28/65k-cpp#8]
How about moving your Cmake build script towards CPM? This would make building much more easy.

**Comment by matheusgomes28** [comment]
Sorry for the delayed reply on this.

I had taken a look at CPM, I definitely like the project and it looks to be a good alternative to both cmake and vcpkg.

However, I cannot make the switch yet because Conan is a little more stable than CPM, and therefore probably a better choice for bringing complex dependencies like `raylib`.

**Comment by matheusgomes28** [comment]
I changed my mind after playing with `CPM` for a little bit.

Thanks for suggesting CPM. For this use-case, it works fairly well as this project doesn't have any dependencies that aren't open-source and CMake-based.

The PR which implemented this was #34

**Comment by vschwaberow** [comment]
Many thanks  for the feedback.
